---
- name: Install sudo
  pacman: name=sudo state=present
  tags:
  - sudo

- name: Create sudo group
  group: name=sudo state=present
  tags:
  - sudo

- name: Copy sudo configuration
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 440
    validate: visudo -cf %s
  tags:
  - sudo

- name: Add user to sudo group
  loop: "{{ admin_users | flatten(levels=1) }}"
  user:
    name: "{{ item.name }}"
    groups: "{{ sudo_group }}"
    append: yes
  tags:
  - sudo
  - user
