---
- name: Create user group
  loop: "{{ admin_users | flatten(levels=1) }}"
  group:
    name: "{{ item.name }}"
    gid: "{{ item.uid }}"
    state: present
  tags:
  - user

- name: Create user
  loop: "{{ admin_users | flatten(levels=1) }}"
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell }}"
    # create with empty password -> first login is easy and obvious
    password: ""
    update_password: on_create
  tags:
  - user

- include_tasks: user-inner-dir.yml
  loop: "{{ admin_users | flatten(levels=1) }}"
  loop_control:
    loop_var: user
#  tags:
#  - user
