---
- name: Create user home directories
  file:
    path: /home/{{ user.name }}/{{ item }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  with_items:
  - data
  - bin
  - tmp
  tags:
  - user
